branch-defaults:
  master:
    environment: flask-env
    group_suffix: null
environment-defaults:
  flask-env:
    branch: null
    repository: null
global:
  application_name: blueskystoursjamaica
  branch: null
  default_ec2_keyname: null
  default_platform: python2.7
  default_region: us-west-2
  profile: eb-cli
  repository: null
  sc: git
